server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kb?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
logging:
  level:
    com.itheima: debug
  pattern:
    dateformat: HH:mm:ss
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#mybatis-plus:
#  type-aliases-package: com.itheima.mp.domain.po
#  global-config:
#    db-config:
#      id-type: auto
#      logic-delete-field: deleted #配置逻辑删除字段
kb:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    user-secret-key: ilovebjtu
    # 设置jwt过期时间
    user-ttl: 7200000
    # 设置前端传递过来的令牌名称，注意：在全局参数中要改为这个名字！要不然会获取不到token
    user-token-name: token



knife4j:
  enable: true
  openapi:
    title: 用户管理接口文档
    description: "用户管理接口文档"
    email: zhanghuyi@itcast.cn
    concat: HaoJie Feng
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.aa.knowledgebase.controller